apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - mariadb/deployment.yaml
  - mariadb/service.yaml
  - mariadb/storage.yaml
  - booklore/deployment.yaml
  - booklore/service.yaml
  - booklore/storage.yaml
 
