apiVersion: apps/v1
kind: Deployment
metadata:
  name: baikal
  namespace: baikal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baikal
  template:
    metadata:
      labels:
        app: baikal
    spec:
      containers:
        - name: baikal
          image: ckulka/baikal:nginx  # nginx variant is the cleanest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /var/www/baikal/specific
              subPath: specific
            - name: data
              mountPath: /var/www/baikal/config
              subPath: config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: baikal-data
